version: '3.8'

services:
  db:
    image: postgres:15
    container_name: roadmapprojectfastapi-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: roadmapprojectfastapi-redis-1
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: roadmapprojectfastapi-app-1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/delivery
      - REDIS_URL=redis://redis:6379/0
#    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    networks:
      - app-network

  celery-worker:
    build: .
    container_name: roadmapprojectfastapi-celery-worker-1
    command: celery -A src.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/delivery
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network

  celery-beat:
    build: .
    container_name: roadmapprojectfastapi-celery-beat-1
    command: celery -A src.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/delivery
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge